const Router = require("express").Router()

const BrandRouter = require("./BrandRoutes")
const MaincategoryRouter = require("./MaincategoryRoutes")
const SubcategoryRouter = require("./SubcategoryRoutes")
const ProductRouter = require("./ProductRoutes")
const FeatureRouter = require("./FeatureRoutes")
const FaqRouter = require("./FaqRoutes")
const SettingRouter = require("./SettingRoutes")
const UserRouter = require("./UserRoutes")
const CartRouter = require("./CartRoutes")
const WishlistRouter = require("./WishlistRoutes")
const AddressRouter = require("./AddressRoutes")
const CheckoutRouter = require("./CheckoutRoutes")
const TestimonialRouter = require("./TestimonialRoutes")
const NewsletterRouter = require("./NewsletterRoutes")
const ContactUsRouter = require("./ContactUsRoutes")

Router.use("/maincategory", MaincategoryRouter)
Router.use("/subcategory", SubcategoryRouter)
Router.use("/brand", BrandRouter)
Router.use("/product", ProductRouter)
Router.use("/feature", FeatureRouter)
Router.use("/faq", FaqRouter)
Router.use("/setting", SettingRouter)
Router.use("/user", UserRouter)
Router.use("/cart", CartRouter)
Router.use("/wishlist", WishlistRouter)
Router.use("/address", AddressRouter)
Router.use("/checkout", CheckoutRouter)
Router.use("/testimonial", TestimonialRouter)
Router.use("/newsletter", NewsletterRouter)
Router.use("/contactus", ContactUsRouter)

module.exports = Router